// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Pr1-sE_yOwJwm33Wq_s2HoRoaiTw-Mo',
    appId: '1:228500311166:web:54a4ad3a998c261cecdc2f',
    messagingSenderId: '228500311166',
    projectId: 'ecclesia-936f6',
    authDomain: 'ecclesia-936f6.firebaseapp.com',
    storageBucket: 'ecclesia-936f6.firebasestorage.app',
    measurementId: 'G-CB4CMN7B05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPXPFHagkqdhHd6Ua62dBvhzEIocLPeaI',
    appId: '1:228500311166:android:202cc8fb8a4ede38ecdc2f',
    messagingSenderId: '228500311166',
    projectId: 'ecclesia-936f6',
    storageBucket: 'ecclesia-936f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cB7h0dghag10Rc0DH3rayTQL32rmCMw',
    appId: '1:228500311166:ios:183f9e0dcf4e6a96ecdc2f',
    messagingSenderId: '228500311166',
    projectId: 'ecclesia-936f6',
    storageBucket: 'ecclesia-936f6.firebasestorage.app',
    iosClientId: '228500311166-qm3eam2ssv4uipjli5l1diul4f715eg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecclesiaFlutter',
  );
}
